[pgr21]
title = "Pgr21 ─ 연예"
url = "https://ppt21.com/spoent/0?1=1&category=2"
entrySelector = "tbody tr[class='listtr']"
titleSelector = "td.tdsub a"
linkSelector = "td.tdsub a"
contentSelector = "td.tdname span"
waitUntil = "networkidle"

[theqoo_ktalk]
title = "더쿠 ─ 케이돌토크"
url = "https://theqoo.net/index.php?mid=ktalk&filter_mode=normal&category=21832056"
entrySelector = "div.in_content table.bd_lst.bd_tb_lst.bd_tb.theqoo_board_table tr:not(.notice):not(:first-child)"
titleSelector = "td.title a span"
linkSelector = "td.title a"
contentSelector = "tr td.no"
waitUntil = "networkidle"
